name: Upload Godot artifact
description: Upload the Godot artifact.
inputs:
  name:
    description: The artifact name.
    default: "${{ github.job }}"
  path:
    description: The path to upload.
    required: true
    default: "bin/*"
  retention-days:
    description: Retention days for the artifact
    required: false
    default: 14

runs:
  using: "composite"
  steps:
    - name: Upload Godot Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: ${{ inputs.retention-days }}
