name: 🤖 Android Builds
on:
  workflow_call:
    secrets:
      R2_ACCESS_KEY_ID:
        required: true
      R2_SECRET_ACCESS_KEY:
        required: true
      R2_ENDPOINT:
        required: true
      R2_BUCKET:
        required: true

# Global Settings
env:
 # TODO: SCONS_FLAGS from 4.5 diff
 # SCONS_FLAGS: >-
 #   dev_mode=yes
 #   module_text_server_fb_enabled=yes
 #   tests=no
 #   swappy=yes

  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: 4.4
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=yes module_text_server_fb_enabled=yes 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android-template:
    runs-on: "warp-ubuntu-2204-x64-2x"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Template
          cache-name: android-template
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Restore Godot build cache
      uses: ./.github/actions/godot-cache-restore
      with:
        cache-name: ${{ matrix.cache-name }}
      continue-on-error: true

    - name: Setup python and scons
      uses: ./.github/actions/godot-deps

    - name: Download pre-built Android Swappy Frame Pacing Library
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        repo: godotengine/godot-swappy
        version: tags/from-source-2025-01-31
        file: godot-swappy.7z
        target: swappy/godot-swappy.7z

    - name: Extract pre-built Android Swappy Frame Pacing Library
      run: 7za x -y swappy/godot-swappy.7z -o${{github.workspace}}/thirdparty/swappy-frame-pacing

    # - name: Compilation (arm32)
    #   uses: ./.github/actions/godot-build
    #   with:
    #     sconsflags: ${{ env.SCONSFLAGS }} arch=arm32
    #     platform: android
    #     target: ${{ matrix.target }}
    #     tests: false

    - name: Compilation release (arm64)
      uses: ./.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }} arch=arm64 swappy=yes
        platform: android
        target: template_release
        tests: false

    - name: Compilation debug (arm64)
      uses: ./.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }} arch=arm64 swappy=yes
        platform: android
        target: template_debug
        tests: false

    - name: Save Godot build cache
      uses: ./.github/actions/godot-cache-save
      with:
        cache-name: ${{ matrix.cache-name }}
      continue-on-error: true

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
    - name: Generate Godot templates
      run: |
        cd platform/android/java
        ./gradlew generateGodotTemplates
        cd ../../..
        ls -l bin/

    - name: Upload artifact to R2
      uses: ./.github/actions/upload-r2
      with:
        name: ${{ matrix.cache-name }}
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        R2_BUCKET: ${{ secrets.R2_BUCKET }}
        run-id: ${{ github.run_id }}
