name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  GODOT_BASE_BRANCH: 4.3
  SCONSFLAGS: verbose=yes warnings=no production=yes use_lto=yes

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-ios
  cancel-in-progress: true

jobs:
  ios-template:
    runs-on: "macos-latest"
    strategy:
      matrix:
        include:
          - target: template_release
            ios_simulator: no
            arch: arm64
          - target: template_debug
            ios_simulator: no
            arch: arm64
          - target: template_release
            ios_simulator: yes
            arch: arm64
          - target: template_debug
            ios_simulator: yes
            arch: arm64
    name: Template (target=${{ matrix.target }}, ios_simulator=${{ matrix.ios_simulator }}, arch=${{ matrix.arch }})

    steps:
      - uses: actions/checkout@v4

      - name: Setup Godot build cache restore
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.target }}_${{ matrix.arch }}_${{ matrix.ios_simulator }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation (${{matrix.arch}})
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ios_simulator=${{ matrix.ios_simulator }} arch=${{ matrix.arch }}
          platform: ios
          target: ${{ matrix.target }}
          tests: false

      - name: Setup Godot build cache restore
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.target }}_${{ matrix.arch }}_${{ matrix.ios_simulator }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          retention-days: 1
