name: 🐧 Linux Builds
on:
  workflow_call:

# Global Settings
env:
 # TODO: SCONS_FLAGS from 4.5 diff
  # SCONS_FLAGS: >-
  #   dev_mode=yes
  #   module_text_server_fb_enabled=yes
  #   "accesskit_sdk_path=${{ github.workspace }}/accesskit-c-0.17.0/"
  GODOT_CPP_BRANCH: 4.4
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: 4.4
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes strict_checks=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  ASAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/asan.txt
  LSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/lsan.txt
  TSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/tsan.txt
  UBSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/ubsan.txt

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    name: ${{ matrix.name }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor)
            cache-name: linux-editor
            target: editor
            sconsflags: production=yes
            bin: "./bin/godot.linuxbsd.editor.x86_64"
            binMoved: "./bin/linux_editor.x86_64"

          - name: Template (target=template_release)
            cache-name: linux-template-release
            target: template_release
            sconsflags: production=yes
            bin: "./bin/godot.linuxbsd.template_release.x86_64"
            binMoved: "./bin/linux_release.x86_64"

          - name: Template (target=template_debug)
            cache-name: linux-template-debug
            target: template_debug
            sconsflags: production=yes
            bin: "./bin/godot.linuxbsd.template_debug.x86_64"
            binMoved: "./bin/linux_debug.x86_64"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Need newer mesa for lavapipe to work properly.
      - name: Linux dependencies for tests
        if: ${{ matrix.proj-test }}
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB8B81E14DA65431D7504EA8F63F0F2B90935439
          sudo add-apt-repository "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
          sudo apt-get install -qq mesa-vulkan-drivers

      # TODO: Figure out somehow how to embed this one.
      - name: wayland-scanner dependency
        run: |
          sudo apt-get install libwayland-bin

      - name: Free disk space on runner
        run: |
          echo "Disk usage before:" && df -h
          sudo rm -rf /usr/local/lib/android
          echo "Disk usage after:" && df -h

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        if: ${{ ! matrix.legacy-scons }}
        uses: ./.github/actions/godot-deps

      - name: Setup Python and SCons (legacy versions)
        if: ${{ matrix.legacy-scons }}
        uses: ./.github/actions/godot-deps
        with:
          # Sync with Ensure*Version in SConstruct.
          python-version: 3.6
          scons-version: 3.1.2

      - name: Setup GCC problem matcher
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Download pre-built AccessKit
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: AccessKit/accesskit-c
          version: tags/0.17.0
          file: accesskit-c-0.17.0.zip
          target: accesskit-c-0.17.0/accesskit_c.zip

      - name: Extract pre-built AccessKit
        run: unzip -o accesskit-c-0.17.0/accesskit_c.zip

      - name: Install mold linker
        if: matrix.proj-test
        uses: rui314/setup-mold@v1

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} ${{ matrix.scons-flags }}
          platform: linuxbsd
          target: ${{ matrix.target }}
          tests: false

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*
          ls -la
          mv ${{ matrix.bin }} ${{ matrix.binMoved }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
