name: Process templates
on:
  workflow_call:

# Global Settings
env:
  GODOT_VERSION: 4.3

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-process-templates
  cancel-in-progress: true

jobs:
  process-templates:
    runs-on: "ubuntu-22.04"
    name: Process Godot Templates

    steps:
      - name: Download artifacts from ios-template
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Download Godot Templates
        run: |
          curl -L -o Godot_export_templates.tpz https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          unzip Godot_export_templates.tpz

      - name: Uncompress ios.zip from Godot Templates
        run: unzip -q templates/ios.zip -d ios

      - name: Prepare iOS Files
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          ls -la ./artifacts/
          tree ./artifacts/

          cp ./artifacts/ios-template-debug/libgodot.ios.template_debug.arm64.a ios/libgodot.ios.debug.xcframework/ios-arm64/libgodot.a
          cp ./artifacts/ios-template-release/libgodot.ios.template_release.arm64.a ios/libgodot.ios.release.xcframework/ios-arm64/libgodot.a
          cp ./artifacts/ios-template-debug-simulator/libgodot.ios.template_debug.arm64.simulator.a ios/libgodot.ios.debug.xcframework/ios-arm64_x86_64-simulator/libgodot.a
          cp ./artifacts/ios-template-release-simulator/libgodot.ios.template_release.arm64.simulator.a ios/libgodot.ios.release.xcframework/ios-arm64_x86_64-simulator/libgodot.a
          cd ios
          zip -q -9 -r ../ios.zip .
          cd ..
          cp ios.zip templates/ios.zip

      - name: Compress selected template files
        run: |
          mkdir -p compressed_templates templates

          files_to_compress=(
            "templates/ios.zip"
            "artifacts/android-template-debug/android_debug.apk"
            "artifacts/android-template-release/android_release.apk"
            "artifacts/android-template-release/android_source.zip"
            "artifacts/linux-template-debug/linux_debug.x86_64"
            "artifacts/linux-template-release/linux_release.x86_64"
            "templates/version.txt"
            "artifacts/windows-template-debug/windows_debug_x86_64.exe"
            "artifacts/windows-template-release/windows_release_x86_64.exe"
          )

          for file in "${files_to_compress[@]}"; do
            target_path="templates/$(basename "$file")"

            # Only move if the file is not already inside templates/
            if [[ "$file" != "$target_path" ]]; then
              mv "$file" "$target_path" 2>/dev/null || true
            fi

            # Compress it, keeping the "templates/" folder inside the ZIP
            zip -q -9 -r "compressed_templates/$(basename "$file").zip" "templates/$(basename "$file")"
          done

          editor_to_compress=(
            "artifacts/macos-editor/godot.macos.editor.universal"
            "artifacts/linux-editor/linux_editor.x86_64"
            "artifacts/windows-editor/windows_editor_x86_64.exe"
          )

          for file in "${editor_to_compress[@]}"; do
            zip -q -9 -j "compressed_templates/$(basename "$file").zip" "$file" --junk-paths
          done

      - name: Upload templates
        uses: actions/upload-artifact@v4
        with:
          name: templates
          retention-days: 1
          path: compressed_templates
